import express from "express";
import authRouter from "./auth.route";
import companyRouter from "./company.route";
import viewRouter from "./view.route";
import configurationRouter from "./configuration.route";
import department from "./department.route";
import userRouter from "./user.route";
import jobRoleRouter from "./job-role.route";
import insightRouter from "./insight.route";
import leaveManagementRouter from "./holiday.route";
import projectRouter from "./project.route";
import storageRouter from "./storage.route";
import taskRoute from "./task.route";
import insightTypeRouter from "./insight-type.route";
import organizationRouter from "./organization.route";
import empPersonalDetailsRouter from "./emp-personal-details.route";
import holidayRouter from "./holiday.route";
import leaveRouter from "./leave.route";
import expenseRouter from "./expense.route";
import salarySlabRouter from "./salary-slab.route";
import teamRouter from "./team.route";
const router = express.Router();

router.use("/auth", authRouter);
router.use("/configuration", configurationRouter);
router.use("/department", department);
router.use("/jobRole", jobRoleRouter);
router.use("/user", userRouter);
router.use("/insight", insightRouter);
router.use("/insight-type", insightTypeRouter);
router.use("/holiday", holidayRouter);
router.use("/storage", storageRouter);
router.use("/project", projectRouter);
router.use("/view", viewRouter);
router.use("/super/company", companyRouter);
router.use("/task", taskRoute);
router.use("/organization", organizationRouter);
router.use("/employee", empPersonalDetailsRouter);
router.use("/leave", leaveRouter);
router.use("/expense", expenseRouter);
router.use("/salary-slab", salarySlabRouter);
router.use("/team", teamRouter);

export default router;
