export const apiEndPoints = {
  employer_register: 'super/company',
  login: 'auth/login',
  send_otp: 'auth/send-otp',
  create_employee: 'user/create-employeeDetail',
  configuration_employeeId: 'configuration/configure-employeeId',
  config_attend_time: 'configuration/configure-attendance-timing',
  verify_otp: 'auth/verify-otp',
  reset_pass: 'auth/reset-password',
  change_password: 'auth/change-password',
  generate_employee_id: 'user/generate-employeeId',
  get_all_employeebypage: 'user/get-custom-employee-list',
  get_all_employee: 'user/get-all-employeeDetails',
  last_generated_employee_id: 'user/last-generated-employee-id',
  add_department: 'department/add-department',
  get_all_department: 'department/get-all-department-details',
  add_job_role: 'jobRole/add-job-role',
  get_all_job_role: 'jobRole/get-job-role-by-dep-id',
  get_job_role: 'jobRole/get-all-Job-role-details',
  get_specific_employee_details:
    'employee/employee-get-specified-personal-details',
  deactivate_activate_employee: 'user/employee-status',
  reject_employee: 'user/user-status',
  get_admin_details: 'user/get-admin-profile-details',
  update_admin_details: 'user/update-admin-profile',
  fill_org_details: 'organization/organization-details',
  get_org_details: 'organization/get-organization-details',
  fillter_employees: 'user/filter-employee-list',
  get_configure_attendance_time:
    'configuration/configure-get-attendance-timing',
  update_office_time: 'configuration/configure-update-attendance-timing',
  assign_shift: 'user/assign-shift',
  add_holiday: 'holiday/add-holiday',
  get_holiday: 'holiday/get-holiday-list',
  dele_holiday: 'holiday/remove-holiday',
  update_holiday: 'holiday/update-holiday',
  total_leave: 'leave/admin-leave-request-list',
  single_request: 'leave/admin-get-separate-leave-request-list',
  update_leave: 'leave/update-leave-status',
  get_attendance_report: 'user/attendance-report',
  specific_att_resport: 'user/get-attendance-report',
  leave_filter: 'leave/leave-search?text=',
  employee_filter: 'user/search-employee?text=',
  attendance_fillter: 'user/search-attendance?text=',
  upload_dp: 'storage?actionType',
  insert_filename: 'user/employee-upload-profile-image',
  monthly_annual_report: 'user/monthly-yearly-complete-report?userId=',
  filter_employee: 'user/filter-employee',
  get_leave_request: 'leave/filter-leave-request',
  filter_attendance_report: 'user/filter-attendance-report',
  create_team: 'team/add',
};
