apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-deployment
  labels:
    app: main
spec:
  replicas: 3
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - name: netclack-backend
        image: netclack-backend
        imagePullPolicy: Never
        ports:
        - containerPort: 4000
        resources:
          limits:
            memory: 1500Mi
            cpu: "4"
          requests:
            memory: 1500Mi
            cpu: "4"