apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: gateway-image
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-srv
spec:
  type: NodePort
  selector:
    app: gateway-service
  ports:
    - name: auth
      protocol: TCP
      port: 4002
      targetPort: 8082
